services:
  mf_db:
    image: postgres
    restart: always
    container_name: mf_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mutual_funds  
    ports:
      - "5432:5432"
    networks:
      - mf_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mf_redis:
    image: redis:latest
    container_name: mf_redis
    ports:
      - "6379:6379"
    networks:
      - mf_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mf_network:
    driver: bridge