services:
  mf_db:
    image: postgres
    restart: always
    container_name: mf_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mutual_funds  
    ports:
      - "5432:5432"