[project]
name = "mutual-fund"
version = "0.1.0"
description = "Mutual Fund API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.6",
]

[dependency-groups]
dev = [
    "ruff>=0.8.5",
]
